### ISSUE TITLE
API - Send Commands (Simple)

### ISSUE THREAD

**Issue by flinke-flasche** [lukasroegner/homebridge-apple-tv-remote#67]
Hi, 
Thank you for the implementation. 
I'm new in homebridge. I'm still learning.

Is it possible to send the other commands like up, down etc.?

I have problems to send the APIToken with my Remote Control App "Demopad".
Is it necessary to use a Token for the commands?

Thank you

**Comment by capdav** [comment]
Hi,

Thanks a lot for the feature, I have the same problem with API token which is mandatory in the header. As it is Simple HTTP request, some drivers only allows you to set the request only (no header, no body, ..). 

Same request as flinke-flasche, would be really appreciate to support the same command as REST one. Could I suggest something like:
http://<YOUR-HOST-IP-ADDRESS>:<apiPort>/<UNIQUE-NAME>/sendcommand?command=menu

Anyway, the plugin is stable and look really great!

**Comment by RaymondMouthaan** [comment]
It's nice that @lukasroegner added the "simple http request" to the plugin, but in my opinion these tools that require this, simply do not respect the REST principles and sound more an issue to these tools instead of this plugin. Any chance requesting modifications to these tools instead of requesting it here?

**Comment by capdav** [comment]
Hi, 
Unfortunately we are talking about legacy drivers.
The purpose of this request is to have a simple http request support that does the same as the REST api. So, indeed, it doesn’t respect REST because this is not REST ;-)

**Comment by RaymondMouthaan** [comment]
Perhaps a nice opportunity to find a beter alternative for these legacy drivers ;-)

**Comment by capdav** [comment]
I tried without success :-( but maybe I didn’t try enough.

I can clearly understand if Lukas decide to stop siding more hours on this request.

**Comment by RaymondMouthaan** [comment]
I am not familiar with these legacy drivers, but you might want to dive into Node-RED (https://nodered.org) .. it can help you to "translate" these http request used by the legacy drivers into the REST calls required by homebridge-apple-tv-remote. 

For example: let the legacy drivers communicate with Node-RED, create a flow to change the http request so that homebridge-apple-tv-remote understands it.

**Comment by lukasroegner** [comment]
Latest version now supports simple key presses and token via query parameter.
I also highly suggest taking a look into Node-RED!

**Comment by capdav** [comment]
Excellent suggestion!
